# JumpPorts Default Configuration
debug: false
useFancyConsole: true
quitSelection: false
overrideTeleport: true
afterEffect: true
afterEffects:
  CONFUSION:
    duration: 100
    amplifier: 5
beginEffect: true
beginEffects:
  CONFUSION:
    duration: 100
    amplifier: 5
harmlessLightningLeave: false
harmlessLightningArrive: false
teleportDelay: 50
triggers:
  sneak: false
  sprint: false
  jump: true
  fall: false
  fireArrow: false
  eggThrow: false
portDefaults:
  description: ""
  enabled: true
  instant: false
  price: 0.00
  isTeleport: true
  cmdPortal: false