# JumpPorts Default Configuration
# R2.0 - Added comments and descriptions
# - TruDan

#################################################
# Valid Effects (Used later down in the config) #
# Note: Some of these may be 1.7 only, so check #
# beforehand!                                   #
#################################################
# ABSORPTION        - Increases the maximum health of an entity with health that cannot be regenerated, but is refilled every 30 seconds.
# BLINDNESS         - Blinds an entity.
# CONFUSION         - Warps vision on the client.
# DAMAGE_RESISTANCE - Decreases damage dealt to an entity.
# FAST_DIGGING      - Increases dig speed.
# FIRE_RESISTANCE   - Stops fire damage.
# HARM              - Hurts an entity.
# HEAL              - Heals an entity.
# HEALTH_BOOST      - Increases the maximum health of an entity.
# HUNGER            - Increases hunger.
# INCREASE_DAMAGE   - Increases damage dealt.
# INVISIBILITY      - Grants invisibility.
# JUMP              - Increases jump height.
# NIGHT_VISION      - Allows an entity to see in the dark.
# POSION            - Deals damage to an entity over time.
# REGENERATION      - Regenerates Health.
# SATURATION        - Increases the food level of an entity each tick.
# SLOW              - Decreases movement speed.
# SLOW_DIGGING      - Decreases dig speed.
# SPEED             - Increases movement speed.
# WATER_BREATHING   - Allows breathing underwater.
# WEAKNESS          - Decreases damage dealt by an entity.
# WITHER            - Deals damage to an entity over time and gives health to the shooter.
#################################################

# Actual Config stuff! #

############################
# debug : (true|false)     #
# Default: false           #
# Enable debugging output? #
############################
debug: false

####################################
# useFancyConsole: (true|false)    #
# Default: true                    #
# Enable coloured logs in console? #
####################################
useFancyConsole: true

##################################
# quitSelection: (true|false)    #
# Default: false                 #
# Automatically stop selecting a #
# region after creating a port   #
##################################
quitSelection: false

######################################
# overrideTeleport: (true|false)     #
# Default: true                      #
# Do you want to apply the global    #
# after effects for any kind of      #
# teleportation (from other plugins) #
######################################
overrideTeleport: true




####################################################
# Port Configuration                               #
####################################################
# This is a fairly large explination of each part  #
# the config nodes should be self-explanitory, so  #
# you may not even need this guide, however some   #
# may find it helpful.                             #
####################################################

####################################################
# GlobalPortConfig is the 'default' port           #
# configuration. By default, ports will be         #
# setup with the settings you provide here.        #
# However, if you make a port 'standalone'         #
# the port will no longer rely on these settings   #
# and will continue to use its own set ones.       #
# When you change a port to 'standalone' it will   #
# copy these settings as defaults, then you alter  #
# what you desire. If you change a port back to    #
# 'default' then it will delete all of its current #
# configuration and use the GlobalPortConfig.      #
####################################################

###########################
# enabled: (true|false)   #
# Default: true           #
# Enable/Disable the port #
###########################

##############################################
# description: (String)                      #
# Default: ""                                #
# The message that appears when              #
# the player is requested to trigger         #
# e.g "Jump to teleport to Lonely Mountain!" #
#                                            #
# Note: If left blank ("") nothing will be   #
# displayed to the player.                   #
##############################################

#######################################
# permissionNode: (String)            #
# Default: ""                         #
# This is an OPTIONAL permission node #
# that is required by the user        #
# in order to use the port. This is   #
# more designed for 'standalone'      #
# ports, and players will by default  #
# need the 'jumpports.use' permission #
# in order to use ANY ports.          #
#######################################

######################################
# instant: (true|false)              #
# Default: false                     #
# If you want to make the port have  #
# no delays, no triggers then set    #
# this to true, then no triggers     #
# will be checked and the player     #
# will be teleported as soon as they #
# enter the region                   #
######################################

##################################
# price: (Decimal)               #
# Default: 0.00                  #
# This is the price of the port, #
# JumpPorts uses Vault for       #
# economy.                       #
##################################

######################################
# isTeleport: (true|false)           #
# Default: true                      #
# It is possible to setup command    #
# regions in JumpPorts, and not      #
# have ANY teleporting, you can      #
# setup a region, to execute         #
# player AND/OR console commands     #
# when the player triggers the       #
# portal (unless it is "instant")    #
#                                    #
# Note: You can also have the portal #
#       execute commands, AND        #
#       teleport. This option simply #
#       tells JumpPorts to not       #
#       even worry about teleporting #
#       for this specific port.      #
######################################

###################################
# cmdPortal: (true|false)         #
# Default: false                  #
# Will this portal have commands  #
# assigned to it? (to be executed #
# by the player and/or console?   #
# if so, make this true.          #
###################################

#######################################
# useGlobalConfig: (true|false)       #
# Default: true                       #
# This is where you choose to be      #
# simple, or complicated!             #
#                                     #
# Setting this to true (Simple)       #
# means the ports you create          #
# will all use the settings from      #
# the "globalPortConfig"              #
#                                     #
# Setting this to false (Complicated) #
# means the port will NOT use the     #
# global settings, and instead use    #
# its own. This only applies to       #
# Begin/After effects.                #
#######################################

#############################
# afterEffect: (true|false) #
# Default: true             #
# Enable after effects?     #
#############################

####################################################
# afterEffects: (See Below)                        #
#                                                  #
# These are potion effects that can be applied to  #
# a player after they have been teleported         #
# Refer to the Valid Effects at the top of this    #
# config file to see all of the effects you can    #
# use.                                             #
# the 'duration' parameter is how long (in ticks)  #
# the player will have the effect for.             #
#                                                  #
# The 'amplifier' effect is the strength of the    #
# effect, e.g. if the potion was SPEED and the     #
# amplifier was '2' the effect would be Speed II   #
####################################################
# Example:                                         #
####################################################
#   afterEffects:                                  #
#     CONFUSION:                                   #
#       duration: 100                              #
#       amplifier: 1                               #
#     HEALTH_BOOST:                                #
#       duration: 10                               #
#       amplifier: 5                               #
####################################################

####################################################
# beginEffects: (See After Effects)                #
####################################################
# These are used on the same basis as the after    #
# effects, however, instead of being applied to    #
# the player AFTER they teleport, these are added  #
# to the player BEFORE they teleport (as soon as   #
# they trigger the port)                           #
# the 'duration' parameter is how long (in ticks)  #
#                                                  #
# For an example, see the afterEffects setup. Just #
# use beforeEffects instead of afterEffects.       #
####################################################

########################################
# harmlessLightningLeave: (true|false) #
# Default: false                       #
# Creates a lightning strike where the #
# player is, when they're about to     #
# teleport                             #
########################################

#########################################
# harmlessLightningArrive: (true|false) #
# Default: false                        #
# Creates a lightning strike where the  #
# player is, after they teleport (and   #
# arrive at the teleport location       #
#########################################

########################################
# teleportDelay: 0 - Integer.MAX_VALUE #
# Default: 50 (2.5 seconds)            #
# The time it takes for the teleport   #
# to actually happen ONCE they trigger #
# the port.                            #
########################################

####################################
# Triggers                         #
# These are the different methods  #
# of triggering a port, these must #
# occur when they are within the   #
# port region.                     #
####################################
# sneak: (true|false)              #
# Default: false                   #
# Trigger when the player sneaks   #
#                                  #
# sprint: (true|false)             #
# Default: false                   #
# Trigger when the player sprints  #
#                                  #
# jump: (true|false)               #
# Default: true                    #
# Trigger when the player jumps    #
#                                  #
# fall: (true|false)               #
# Default: false                   #
# Trigger when the player falls    #
#                                  #
# fireArrow: (true|false)          #
# Default: false                   #
# Trigger when the player fires a  #
# bow.                             #
#                                  #
# eggThrow: (true|false)           #
# Default: false                   #
# Trigger when the player throws   #
# an egg.                          #
####################################

###############################################
# See above for the notes on globalPortConfig #
# I've kept these all together for the people #
# that know what they're doing, and to make   #
# it easier to read/edit.                     #
###############################################

#################################################
# Global config is two things.                  #
# 1) The default for ALL new ports              #
# 2) The "global" settings for all ports which  #
#    have "useGlobalConfig:true". Note that the #
#    only "global" settings are afterEffects,   #
#    beginEffects, harmlessLightning, triggers  #
#################################################

globalPortConfig:
  description: ""
  enabled: true
  permissionNode: ""
  instant: false
  price: 0.00
  isTeleport: true
  isBungee: false
  cmdPortal: false
  useGlobalConfig: true
  afterEffect: true
  afterEffects:
    CONFUSION:
      duration: 80
      amplifier: 1
  beginEffect: true
  beginEffects:
    CONFUSION:
      duration: 80
      amplifier: 1
  harmlessLightningLeave: false
  harmlessLightningArrive: false
  teleportDelay: 50
  triggers:
    sneak: false
    sprint: false
    jump: true
    fall: false
    fireArrow: false
    eggThrow: false