name: ${project.name}
main: net.dwdg.jumpports.JumpPortsPlugin
version: ${project.version}
depends: [Vault]
dev-url: ${project.url}
commands:
    jp:
      usage: /jp
      description: General JumpPorts Commands
    jumpports:
      usage: /jumpports
      description: General JumpPorts Commands